name: 'Unreal Engine Action'
description: 'Build an Unreal Engine plugin or project'
author: 'Daniel Asztalos'
inputs:
  unreal-engine-version:
    required: true
    description: 'The version of Unreal Engine to use'
  plugin-path:
    required: true
    description: 'The path to the plugin to be built'
  output-path:
    required: true
    description: 'The path of the output'
  VS2019:
    description: 'Use Visual Studio 2019 for compiling all targets'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
